uint32 target_type

uint32 TARGET_TYPE_STANDARD = 1
uint32 TARGET_TYPE_EMERGENT = 2

uint32 target_hub 

uint32 shape

uint32 SHAPE_CIRCLE = 1 
uint32 SHAPE_SEMI_CIRCLE = 2
uint32 SHAPE_QUARTER_CIRCLE = 3
uint32 SHAPE_TRIANGLE = 4
uint32 SHAPE_RECTANGLE = 5
uint32 SHAPE_PENTAGON = 6
uint32 SHAPE_STAR = 7
uint32 SHAPE_CROSS = 8

uint32 shape_color 

uint32 COLOR_WHITE = 1
uint32 COLOR_BLACK = 2
uint32 COLOR_RED = 3
uint32 COLOR_BLUE = 4
uint32 COLOR_GREEN = 5
uint32 COLOR_PURPLE = 6
uint32 COLOR_BROWN = 7
uint32 COLOR_ORANGE = 8

char alpha_num

uint32 alpha_num_color
